services:
  - type: web
    name: gestion-produits-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: REMPLACEZ_PAR_VOTRE_CONNECTION_STRING_PLANETSCALE
      - key: JWT_SECRET
        value: votre_secret_jwt_tres_long_et_complexe_pour_production
    healthCheckPath: /
